telegram_token: ""
openai_api_key: ""
openai_api_base: null  # leave null to use default api base or you can put your own base url here
allowed_telegram_usernames: [
    "@dzlob",
    "@dzlob_ton", 
]  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as positive integers and/or channel ids as negative integers
new_dialog_timeout: 7200  # new dialog starts after timeout (in seconds)
return_n_generated_images: 1
n_chat_modes_per_page: 5
image_size: "1024x1024" # the image size for DALL-E 3 image generation. Supported sizes: 1024x1024 (square), 1024x1792 (portrait), 1792x1024 (landscape).
enable_message_streaming: true  # if set, messages will be shown to user word-by-word
default_model: "gpt-4o"
default_image_model: "dall-e-3"

# prices
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006
